### ISSUE TITLE
Whenever I am trying to execute the cell which has plot function, kernel dies.

### ISSUE THREAD

**Issue by wipere786** [edaaydinea/AI-Projects-for-Healthcare#8]
Whenever I am trying to execute the cell which has plot function, kernel dies. How can I resolve this issue?

![Screenshot 2023-03-25 152818](https://user-images.githubusercontent.com/127714116/227710345-8a795bc0-b294-45cd-af02-d97b0c99c5b5.png)

**Comment by edaaydinea** [comment]
```
import os    
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
```
Can you add this code segment before running all the code?
I solved it this way because of the incompatibility I used torch in another project before. I think your problem will be solved.

**Comment by wipere786** [comment]
Thank you so much..

It worked.

**Comment by edaaydinea** [comment]
You're welcome. 🙂
